const dropdownOptions = {
  PositionType: [
    { label: "Sell", value: "PositionType.Sell" },
    { label: "Buy", value: "PositionType.Buy" },
  ],
  ExpiryKind: [
    { label: "Weekly", value: "ExpiryType.Weekly" },
    { label: "Monthly", value: "ExpiryType.Monthly" },
  ],
  EntryType: [
    { value: "EntryType.EntryByStrikeType", label: "Strike Type" },
    { value: "EntryType.EntryByPremium", label: "Premium" },
    { value: "EntryType.EntryByPremiumRange", label: "Premium Range" },
    { value: "EntryType.EntryByStraddleWidth", label: "Straddle Width" },
  ],
  InstrumentKind: [
    { label: "Call", value: "LegType.CE" },
    { label: "Put", value: "LegType.PE" },
  ],
  Adjustments: [
    { label: "+", value: "Plus" },
    { label: "-", value: "Minus" },
  ],
  StrikeType: [
    { label: "ITM20", value: "StrikeType.ITM20" },
    { label: "ITM19", value: "StrikeType.ITM19" },
    { label: "ITM18", value: "StrikeType.ITM18" },
    { label: "ITM17", value: "StrikeType.ITM17" },
    { label: "ITM16", value: "StrikeType.ITM16" },
    { label: "ITM15", value: "StrikeType.ITM15" },
    { label: "ITM14", value: "StrikeType.ITM14" },
    { label: "ITM13", value: "StrikeType.ITM13" },
    { label: "ITM12", value: "StrikeType.ITM12" },
    { label: "ITM11", value: "StrikeType.ITM11" },
    { label: "ITM10", value: "StrikeType.ITM10" },
    { label: "ITM9", value: "StrikeType.ITM9" },
    { label: "ITM8", value: "StrikeType.ITM8" },
    { label: "ITM7", value: "StrikeType.ITM7" },
    { label: "ITM6", value: "StrikeType.ITM6" },
    { label: "ITM5", value: "StrikeType.ITM5" },
    { label: "ITM4", value: "StrikeType.ITM2" },
    { label: "ITM3", value: "StrikeType.ITM3" },
    { label: "ITM10", value: "StrikeType.ITM10" },
    { label: "ITM1", value: "StrikeType.ITM1" },
    { label: "ATM", value: "StrikeType.ATM" },
    { label: "OTM20", value: "StrikeType.OTM20" },
    { label: "OTM19", value: "StrikeType.OTM19" },
    { label: "OTM18", value: "StrikeType.OTM18" },
    { label: "OTM17", value: "StrikeType.OTM17" },
    { label: "OTM16", value: "StrikeType.OTM16" },
    { label: "OTM15", value: "StrikeType.OTM15" },
    { label: "OTM14", value: "StrikeType.OTM14" },
    { label: "OTM13", value: "StrikeType.OTM13" },
    { label: "OTM12", value: "StrikeType.OTM12" },
    { label: "OTM11", value: "StrikeType.OTM11" },
    { label: "OTM10", value: "StrikeType.OTM10" },
    { label: "OTM9", value: "StrikeType.OTM9" },
    { label: "OTM8", value: "StrikeType.OTM8" },
    { label: "OTM7", value: "StrikeType.OTM7" },
    { label: "OTM6", value: "StrikeType.OTM6" },
    { label: "OTM5", value: "StrikeType.OTM5" },
    { label: "OTM4", value: "StrikeType.OTM2" },
    { label: "OTM3", value: "StrikeType.OTM3" },
    { label: "OTM10", value: "StrikeType.OTM10" },
    { label: "OTM1", value: "StrikeType.OTM1" },
  ],
  momentum: [
    { label: "Points Up", value: "MomentumType.PointsUp" },
    { label: "Points Down", value: "MomentumType.PointsDown" },
    { label: "Percentage Up", value: "MomentumType.PercentageUp" },
    { label: "Percentage Down", value: "MomentumType.PercentageDown" },
    { label: "Underlying Point Up", value: "MomentumType.UnderlyingPointUp" },
    {
      label: "Underlying Point Down",
      value: "MomentumType.UnderlyingPointDown",
    },
    {
      label: "Underlying Percentage Up",
      value: "MomentumType.UnderlyingPercentageUp",
    },
    {
      label: "Underlying Percentage Down",
      value: "MomentumType.UnderlyingPercentageDown",
    },
  ],
  trialSL: [
    { label: "Point", value: "TrialStopLossType.Point" },
    { label: "Percentage", value: "TrialStopLossType.Percentage" },
  ],
};

export default dropdownOptions;
